{"Name":"MyCubes","Extrusions":{"2794":{"ExtrusionWrapProperties":{"StartOffset":0.0,"EndOffset":0.82020997375328075,"SketchPlane":[{"SketchOrigin":[0.0,0.0,0.0]},{"SketchNormal":[0.0,0.0,1.0]}],"CurveArrArray":[{"Array1Line1":[-3.1998727267819262,2.5324738042690784,0.0,-3.1998727267819262,1.5482218357651414,0.0]},{"Array1Line2":[-3.1998727267819262,1.5482218357651414,0.0,-4.840292674288488,1.5482218357651414,0.0]},{"Array1Line3":[-4.840292674288488,1.5482218357651414,0.0,-4.840292674288488,2.5324738042690784,0.0]},{"Array1Line4":[-4.840292674288488,2.5324738042690784,0.0,-3.1998727267819262,2.5324738042690784,0.0]}],"FacesOrigins":[{"0":[-4.840292674288488,2.5324738042690784,0.82020997375328075]},{"1":[-4.840292674288488,2.5324738042690784,0.0]},{"2":[-3.1998727267819262,2.5324738042690784,0.82020997375328075]},{"5":[-4.840292674288488,2.5324738042690784,0.82020997375328075]},{"9":[-4.840292674288488,1.5482218357651414,0.82020997375328075]},{"13":[-3.1998727267819262,1.5482218357651414,0.82020997375328075]}],"EdgesCurves":[{"3":[-3.1998727267819262,2.5324738042690784,0.82020997375328075]},{"6":[-4.840292674288488,2.5324738042690784,0.82020997375328075]},{"10":[-4.840292674288488,1.5482218357651414,0.82020997375328075]},{"14":[-3.1998727267819262,1.5482218357651414,0.82020997375328075]},{"15":[-3.1998727267819262,2.5324738042690784,0.0]},{"11":[-3.1998727267819262,1.5482218357651414,0.0]},{"7":[-4.840292674288488,1.5482218357651414,0.0]},{"4":[-4.840292674288488,2.5324738042690784,0.0]},{"17":[-3.1998727267819262,2.5324738042690784,0.82020997375328075]},{"8":[-4.840292674288488,2.5324738042690784,0.82020997375328075]},{"12":[-4.840292674288488,1.5482218357651414,0.82020997375328075]},{"16":[-3.1998727267819262,1.5482218357651414,0.82020997375328075]}],"Visible":false,"IsSolid":true,"doc":null,"Id":2794,"Name":null,"Type":null,"isPinned":false,"Category":null},"Visible":true,"IsSolid":true,"doc":null,"Id":2794,"Name":"Выдавливание","Type":"Autodesk.Revit.DB.Extrusion","isPinned":false,"Category":null}},"Revolutions":{},"Blends":{},"Sweeps":{},"SweptBlends":{},"Dimensions":{"2852":{"DimensionWrapProperties":{"ViewName":"Ref. Level","LineAlongDim":{"Line":[-3.4515167171086674,3.0838995519728307,0.0,1.0,0.0,0.0]},"ReferenceIds":[[2794,5],[2794,13]],"doc":null,"Id":2852,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":2852,"Name":"Linear","Type":"Autodesk.Revit.DB.Dimension","isPinned":false,"Category":"Autodesk.Revit.DB.Category"}}}