{"Name":"MyCubes","Extrusions":{"2794":{"ExtrusionWrapProperties":{"StartOffset":0.0,"EndOffset":0.82020997375328075,"SketchPlane":[{"SketchOrigin":[0.0,0.0,0.0]},{"SketchNormal":[0.0,0.0,1.0]}],"CurveArrArray":[{"Array1Line1":[-1.932322648600147,2.9613604969275524,0.0,-1.932322648600147,1.9771085284236154,0.0]},{"Array1Line2":[-1.932322648600147,1.9771085284236154,0.0,-3.9008265856080211,1.9771085284236154,0.0]},{"Array1Line3":[-3.9008265856080211,1.9771085284236154,0.0,-3.9008265856080211,2.9613604969275524,0.0]},{"Array1Line4":[-3.9008265856080211,2.9613604969275524,0.0,-1.932322648600147,2.9613604969275524,0.0]}],"Visible":false,"IsSolid":true,"doc":null,"Id":2794,"Name":null,"Type":null,"isPinned":false,"Category":null},"Visible":true,"IsSolid":true,"doc":null,"Id":2794,"Name":"Выдавливание","Type":"Autodesk.Revit.DB.Extrusion","isPinned":false,"Category":null}},"Revolutions":{},"Blends":{},"Sweeps":{},"SweptBlends":{},"Dimensions":{"2825":{"DimensionWrapProperties":{"ViewName":"Ref. Level","LineAlongDim":{"Line":[-2.5937433317917211,3.717018003040101,0.0,1.0,0.0,0.0]},"ReferenceIds":[[2794,5],[2794,13]],"doc":null,"Id":2825,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":2825,"Name":"Linear","Type":"Autodesk.Revit.DB.Dimension","isPinned":false,"Category":"Autodesk.Revit.DB.Category"}}}