{"Name":"MyCubes","Extrusions":{"2749":{"ExtrusionWrapProperties":{"StartOffset":0.0,"EndOffset":1.6404199475065617,"SketchPlane":[{"SketchOrigin":[-0.82020997375328086,-0.82020997375328086,0.0]},{"SketchNormal":[0.0,0.0,1.0]}],"CurveArrArray":[{"Array1Line1":[0.82020997375328086,-0.82020997375328086,0.0,0.82020997375328086,0.82020997375328086,0.0]},{"Array1Line2":[0.82020997375328086,0.82020997375328086,0.0,-0.82020997375328086,0.82020997375328086,0.0]},{"Array1Line3":[-0.82020997375328086,0.82020997375328086,0.0,-0.82020997375328086,-0.82020997375328086,0.0]},{"Array1Line4":[-0.82020997375328086,-0.82020997375328086,0.0,0.82020997375328086,-0.82020997375328086,0.0]}],"Id":2749,"IsSolid":true,"Visible":false,"Name":null,"Type":null,"isPinned":false,"Category":null},"Visible":true,"IsSolid":true,"Id":2749,"Name":"Выдавливание","Type":"Autodesk.Revit.DB.Extrusion","isPinned":false,"Category":null},"2756":{"ExtrusionWrapProperties":{"StartOffset":0.0,"EndOffset":2.4606299212598426,"SketchPlane":[{"SketchOrigin":[0.5741469816272966,0.5741469816272966,0.0]},{"SketchNormal":[0.0,0.0,1.0]}],"CurveArrArray":[{"Array1Line1":[3.85498687664042,1.3943569553805775,0.0,3.85498687664042,3.85498687664042,0.0]},{"Array1Line2":[3.85498687664042,3.85498687664042,0.0,1.3943569553805775,3.85498687664042,0.0]},{"Array1Line3":[1.3943569553805775,3.85498687664042,0.0,1.3943569553805775,1.3943569553805775,0.0]},{"Array1Line4":[1.3943569553805775,1.3943569553805775,0.0,3.85498687664042,1.3943569553805775,0.0]}],"Id":2756,"IsSolid":true,"Visible":false,"Name":null,"Type":null,"isPinned":false,"Category":null},"Visible":true,"IsSolid":true,"Id":2756,"Name":"Выдавливание","Type":"Autodesk.Revit.DB.Extrusion","isPinned":false,"Category":null},"2763":{"ExtrusionWrapProperties":{"StartOffset":0.0,"EndOffset":0.82020997375328086,"SketchPlane":[{"SketchOrigin":[-3.5269028871391077,-1.886482939632546,0.0]},{"SketchNormal":[0.0,0.0,1.0]}],"CurveArrArray":[{"Array1Line1":[-1.886482939632546,-0.24606299212598426,0.0,-2.7066929133858304,-0.24606299212598426,0.0]},{"Array1Arc2":[-2.7066929133858304,-0.24606299212598426,0.0,-1.8864829396325462,-1.0662729658792738,0.0,-2.889206802785695,-0.26662736861727077,0.0]},{"Array1Line3":[-1.886482939632546,-1.0662729658792738,0.0,-1.886482939632546,-0.24606299212598426,0.0]}],"Id":2763,"IsSolid":true,"Visible":false,"Name":null,"Type":null,"isPinned":false,"Category":null},"Visible":true,"IsSolid":true,"Id":2763,"Name":"Выдавливание","Type":"Autodesk.Revit.DB.Extrusion","isPinned":false,"Category":null}},"Revolutions":{"2849":{"RevolutionWrapProperties":{"StartingAngle":0.0,"EndingAngle":0.78539816339744828,"PathLineDict":{"PathLine":[-12.360670354653317,-7.365410316526523,0.0,-12.360670354653317,12.634589683473477,0.0]},"SketchPlane":[{"SketchOrigin":[-2.3606703546533163,2.6345896834734774,0.0]},{"SketchNormal":[0.0,0.0,1.0]}],"CurveArrArray":[{"Array1Line1":[-1.3606703546533163,2.6345896834734774,0.0,-1.3606703546533163,3.6345896834734774,0.0]},{"Array1Line2":[-1.3606703546533163,3.6345896834734774,0.0,-2.3606703546533163,2.634589683473477,0.0]},{"Array1Line3":[-2.3606703546533159,2.6345896834734774,0.0,-1.3606703546533163,2.6345896834734774,0.0]}],"Id":2849,"IsSolid":true,"Visible":false,"Name":null,"Type":null,"isPinned":false,"Category":null},"Visible":true,"IsSolid":true,"Id":2849,"Name":"Вращение","Type":"Autodesk.Revit.DB.Revolution","isPinned":false,"Category":null}},"Blends":{"2795":{"BlendWrapProperties":{"TopOffset":1.4763779527559056,"BottomOffset":-1.4763779527559056,"BaseSketchPlane":[{"SketchOrigin":[8.13498986490631,-3.0147509681667763,1.0]},{"SketchNormal":[0.0,0.0,1.0]}],"TopCurveArrArray":[{"Arc1":[3.7394109429518423,-1.5073754840833902,0.0,4.395578921954467,-1.5073754840833862,0.0,3.7591968285207709,-1.6195868171954861,0.0]},{"Arc2":[4.395578921954467,-1.5073754840833882,0.0,3.7394109429518423,-1.5073754840833882,0.0,4.37579303638554,-1.3951641509712922,0.0]}],"BaseCurveArrArray":[{"Line1":[4.8877049062064355,-2.327585457836669,0.0,4.8877049062064355,-0.68716551033010731,0.0]},{"Line2":[4.8877049062064355,-0.68716551033010731,0.0,3.2472849586998738,-0.68716551033010731,0.0]},{"Line3":[3.2472849586998738,-0.68716551033010731,0.0,3.2472849586998738,-2.327585457836669,0.0]},{"Line4":[3.2472849586998738,-2.327585457836669,0.0,4.8877049062064355,-2.327585457836669,0.0]}],"Id":2795,"IsSolid":true,"Visible":false,"Name":null,"Type":null,"isPinned":false,"Category":null},"Visible":true,"IsSolid":true,"Id":2795,"Name":"Переход","Type":"Autodesk.Revit.DB.Blend","isPinned":false,"Category":null}},"Sweeps":{"2829":{"SweepWrapProperties":{"WhichPathLineIsForProfile":0,"AngleFromXZtoY":0.0,"AngleFromYZtoX":0.0,"PathCurveArray":[{"Line1":[-2.5747913883570446,-3.1867510473803389,0.0,-2.5747913883570446,-3.1867510473803389,3.2808398950131235]},{"Line2":[-2.5747913883570446,-3.1867510473803389,3.2808398950131235,3.9868884016692023,-3.1867510473803389,3.2808398950131235]}],"PathSketchPlane":[{"SketchOrigin":[-2.5747913883570446,-3.1867510473803389,0.0]},{"SketchNormal":[0.0,1.0,0.0]}],"ProfileCurveArrArray":[{"Array1Line1":[-1.5747913883570446,-2.1867510473803389,0.0,-4.5747913883570526,-4.1867510473803442,0.0]},{"Array1Line2":[-4.5747913883570508,-4.1867510473803407,0.0,-1.5747913883570441,-3.1867510473803389,0.0]},{"Array1Line3":[-1.5747913883570446,-3.1867510473803389,0.0,-1.5747913883570446,-2.1867510473803389,0.0]}],"ProfileSketchPlane":[{"SketchOrigin":[-2.5747913883570446,-3.1867510473803389,0.0]},{"SketchNormal":[0.0,0.0,1.0]}],"Id":2829,"IsSolid":true,"Visible":false,"Name":null,"Type":null,"isPinned":false,"Category":null},"Visible":true,"IsSolid":true,"Id":2829,"Name":"Модификатор","Type":"Autodesk.Revit.DB.Sweep","isPinned":false,"Category":null}},"SweptBlends":{"2862":{"SweptBlendWrapProperties":{"PathCurve":{"Line":[6.3909828057891378,5.5747913883570508,0.0,6.3909828057891378,5.5747913883570508,3.2808398950131235]},"PathSketchPlane":[{"SketchOrigin":[6.3909828057891378,5.5747913883570508,0.0]},{"SketchNormal":[0.0,1.0,0.0]}],"Profile1CurveArray":[{"Arc1":[5.3909828057891378,5.5747913883570446,0.0,7.3909828057891378,5.574791388357057,0.0,5.4101975253859083,5.3797010663409157,0.0]},{"Arc2":[7.3909828057891378,5.5747913883570508,0.0,5.3909828057891378,5.5747913883570508,0.0,7.3717680861923682,5.7698817103731788,0.0]}],"Profile2CurveArray":[{"Line1":[7.3909828057891378,6.5747913883570508,3.2808398950131235,4.3909828057891289,4.5747913883570455,3.2808398950131235]},{"Line2":[4.3909828057891342,4.57479138835705,3.2808398950131235,7.3909828057891387,5.5747913883570508,3.2808398950131235]},{"Line3":[7.3909828057891378,5.5747913883570508,3.2808398950131235,7.3909828057891378,6.5747913883570508,3.2808398950131235]}],"Profile1SketchPlane":[{"SketchOrigin":[6.3909828057891378,5.5747913883570508,0.0]},{"SketchNormal":[0.0,0.0,1.0]}],"Profile2SketchPlane":[{"SketchOrigin":[6.3909828057891378,5.5747913883570508,3.2808398950131235]},{"SketchNormal":[0.0,0.0,1.0]}],"Id":2862,"IsSolid":true,"Visible":false,"Name":null,"Type":null,"isPinned":false,"Category":null},"Visible":true,"IsSolid":true,"Id":2862,"Name":"Переход по траектории","Type":"Autodesk.Revit.DB.SweptBlend","isPinned":false,"Category":null}}}