{"Name":"Sweep","Extrusions":{},"Revolutions":{},"Blends":{},"Sweeps":{"2748":{"SweepWrapProperties":{"WhichPathLineIsForProfile":0,"AngleFromXZtoY":0.0,"AngleFromYZtoX":0.0,"PathCurveArray":[{"Line1":[0.0,0.0,-1.6404199475065626,0.0,0.0,3.2808398950131235]},{"Line2":[0.0,0.0,3.2808398950131235,6.5616797900262469,0.0,3.2808398950131235]}],"PathSketchPlane":[{"SketchOrigin":[0.0,0.0,0.0]},{"SketchNormal":[0.0,1.0,0.0]}],"ProfileCurveArrArray":[{"Array1Line1":[1.0,1.0,-1.6404199475065626,-2.000000000000004,-1.0000000000000027,-1.6404199475065626]},{"Array1Line2":[-2.0000000000000058,-1.000000000000002,-1.6404199475065626,1.0000000000000004,2.2204460492503131E-16,-1.6404199475065626]},{"Array1Line3":[1.0,-2.2204460492503131E-16,-1.6404199475065626,1.0,1.0,-1.6404199475065626]}],"ProfileSketchPlane":[{"SketchOrigin":[0.0,0.0,-1.6404199475065626]},{"SketchNormal":[0.0,0.0,1.0]}],"Id":2748,"IsSolid":true,"Visible":false,"Name":null,"Type":null,"isPinned":false,"Category":null},"Visible":true,"IsSolid":true,"Id":2748,"Name":"Модификатор","Type":"Autodesk.Revit.DB.Sweep","isPinned":false,"Category":null}},"SweptBlends":{}}