{"Name":"MyCubes","Extrusions":{"2749":{"ExtrusionWrapProperties":{"StartOffset":0.0,"EndOffset":1.6404199475065617,"SketchPlane":[{"SketchOrigin":[-0.82020997375328086,-0.82020997375328086,0.0]},{"SketchNormal":[0.0,0.0,1.0]}],"CurveArrArray":[{"Array1Line1":[0.82020997375328086,-0.82020997375328086,0.0,0.82020997375328086,0.82020997375328086,0.0]},{"Array1Line2":[0.82020997375328086,0.82020997375328086,0.0,-0.82020997375328086,0.82020997375328086,0.0]},{"Array1Line3":[-0.82020997375328086,0.82020997375328086,0.0,-0.82020997375328086,-0.82020997375328086,0.0]},{"Array1Line4":[-0.82020997375328086,-0.82020997375328086,0.0,0.82020997375328086,-0.82020997375328086,0.0]}],"Id":2749,"IsSolid":true,"Visible":false,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"Visible":true,"IsSolid":true,"doc":null,"Id":2749,"Name":"Выдавливание","Type":"Autodesk.Revit.DB.Extrusion","isPinned":false,"Category":null},"2756":{"ExtrusionWrapProperties":{"StartOffset":0.0,"EndOffset":2.4606299212598426,"SketchPlane":[{"SketchOrigin":[0.5741469816272966,0.5741469816272966,0.0]},{"SketchNormal":[0.0,0.0,1.0]}],"CurveArrArray":[{"Array1Line1":[3.85498687664042,1.3943569553805775,0.0,3.85498687664042,3.85498687664042,0.0]},{"Array1Line2":[3.85498687664042,3.85498687664042,0.0,1.3943569553805775,3.85498687664042,0.0]},{"Array1Line3":[1.3943569553805775,3.85498687664042,0.0,1.3943569553805775,1.3943569553805775,0.0]},{"Array1Line4":[1.3943569553805775,1.3943569553805775,0.0,3.85498687664042,1.3943569553805775,0.0]}],"Id":2756,"IsSolid":true,"Visible":false,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"Visible":true,"IsSolid":true,"doc":null,"Id":2756,"Name":"Выдавливание","Type":"Autodesk.Revit.DB.Extrusion","isPinned":false,"Category":null},"2763":{"ExtrusionWrapProperties":{"StartOffset":0.0,"EndOffset":0.82020997375328086,"SketchPlane":[{"SketchOrigin":[-3.5269028871391077,-1.886482939632546,0.0]},{"SketchNormal":[0.0,0.0,1.0]}],"CurveArrArray":[{"Array1Line1":[-1.886482939632546,-1.0662729658792651,0.0,-1.886482939632546,-0.24606299212598426,0.0]},{"Array1Line2":[-1.886482939632546,-0.24606299212598426,0.0,-2.7066929133858268,-0.24606299212598426,0.0]},{"Array1Line3":[-2.7066929133858268,-0.24606299212598426,0.0,-2.7066929133858268,-1.0662729658792651,0.0]},{"Array1Line4":[-2.7066929133858268,-1.0662729658792651,0.0,-1.886482939632546,-1.0662729658792651,0.0]}],"Id":2763,"IsSolid":true,"Visible":false,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"Visible":true,"IsSolid":true,"doc":null,"Id":2763,"Name":"Выдавливание","Type":"Autodesk.Revit.DB.Extrusion","isPinned":false,"Category":null}},"Revolutions":{},"Blends":{},"Sweeps":{},"SweptBlends":{}}