{"Name":"MyCubes","Extrusions":{"2749":{"ExtrusionWrapProperties":{"StartOffset":0.0,"EndOffset":1.6404199475065617,"SketchPlane":[{"SketchOrigin":[-0.82020997375328086,-0.82020997375328086,0.0]},{"SketchNormal":[0.0,0.0,1.0]}],"CurveArrArray":[{"Array1Line1":[1.2795275590551181,-0.82020997375328086,0.0,1.2795275590551181,0.82020997375328086,0.0]},{"Array1Line2":[1.2795275590551181,0.82020997375328086,0.0,-0.82020997375328086,0.82020997375328086,0.0]},{"Array1Line3":[-0.82020997375328086,0.82020997375328086,0.0,-0.82020997375328086,-0.82020997375328086,0.0]},{"Array1Line4":[-0.82020997375328086,-0.82020997375328086,0.0,1.2795275590551181,-0.82020997375328086,0.0]}],"Id":2749,"IsSolid":true,"Visible":false,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"Visible":true,"IsSolid":true,"doc":null,"Id":2749,"Name":"Выдавливание","Type":"Autodesk.Revit.DB.Extrusion","isPinned":false,"Category":null}},"Revolutions":{},"Blends":{},"Sweeps":{},"SweptBlends":{},"Dimensions":{"2891":{"DimensionWrapProperties":{"ViewName":"Ref. Level","LineAlongDim":{"Line":[1.3270378741305375,1.3271813334283218,0.0,1.0,0.0,0.0]},"ReferenceIds":[[2749,9],[2749,2]],"Id":2891,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":2891,"Name":"Linear","Type":"Autodesk.Revit.DB.Dimension","isPinned":false,"Category":"Autodesk.Revit.DB.Category"}}}