{"Name":"Sweep","Extrusions":{},"Revolutions":{},"Blends":{},"Sweeps":{"2748":{"SweepWrapProperties":{"WhichPathLineIsForProfile":0,"AngleFromXZtoY":0.0,"AngleFromYZtoX":0.0,"PathCurveArray":[{"Line1":[-6.5616797900262469,2.1094237467877974E-14,0.0,-6.5616797900262469,2.1094237467877974E-14,3.2808398950131235]},{"Line2":[-6.5616797900262469,2.1094237467877974E-14,3.2808398950131235,0.0,2.1094237467877974E-14,3.2808398950131235]}],"PathSketchPlane":[{"SketchOrigin":[-6.5616797900262469,2.1094237467877974E-14,0.0]},{"SketchNormal":[0.0,1.0,0.0]}],"ProfileCurveArrArray":[{"Array1Line1":[-5.5616797900262469,1.0000000000000211,0.0,-8.561679790026254,-0.9999999999999829,0.0]},{"Array1Line2":[-8.5616797900262469,-0.99999999999997879,0.0,-5.5616797900262469,2.1316282072803006E-14,0.0]},{"Array1Line3":[-5.5616797900262469,2.1760371282653068E-14,0.0,-5.5616797900262469,1.0000000000000211,0.0]}],"ProfileSketchPlane":[{"SketchOrigin":[-6.5616797900262469,2.1094237467877974E-14,0.0]},{"SketchNormal":[0.0,0.0,1.0]}],"Id":2748,"IsSolid":true,"Visible":false,"Name":null,"Type":null,"isPinned":false,"Category":null},"Visible":true,"IsSolid":true,"Id":2748,"Name":"Модификатор","Type":"Autodesk.Revit.DB.Sweep","isPinned":false,"Category":null}},"SweptBlends":{}}