{"Name":"Blend","Extrusions":{},"Revolutions":{},"Blends":{"2750":{"BlendWrapProperties":{"TopOffset":1.4763779527559056,"BottomOffset":-1.4763779527559056,"BaseSketchPlane":[{"SketchOrigin":[1.6404199475065617,6.5616797900262469,1.0]},{"SketchNormal":[0.0,0.0,1.0]}],"TopCurveArrArray":[{"Arc1":[0.49212598425196852,3.2808398950131212,0.0,1.1482939632545932,3.2808398950131257,0.0,0.51191186982089687,3.1686285619010253,0.0]},{"Arc2":[1.1482939632545932,3.2808398950131235,0.0,0.49212598425196852,3.2808398950131235,0.0,1.1285080776856655,3.3930512281252194,0.0]}],"BaseCurveArrArray":[{"Line1":[1.6404199475065617,2.4606299212598426,0.0,1.6404199475065617,4.1010498687664043,0.0]},{"Line2":[1.6404199475065617,4.1010498687664043,0.0,0.0,4.1010498687664043,0.0]},{"Line3":[0.0,4.1010498687664043,0.0,0.0,2.4606299212598426,0.0]},{"Line4":[0.0,2.4606299212598426,0.0,1.6404199475065617,2.4606299212598426,0.0]}],"Id":2750,"IsSolid":true,"Visible":false,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"Visible":true,"IsSolid":true,"doc":null,"Id":2750,"Name":"Переход","Type":"Autodesk.Revit.DB.Blend","isPinned":false,"Category":null}},"Sweeps":{},"SweptBlends":{}}