{"Name":"Revolve","Extrusions":{},"Revolutions":{"2749":{"RevolutionWrapProperties":{"StartingAngle":0.0,"EndingAngle":0.78539816339744828,"PathLineDict":{"PathLine":[-10.0,-10.0,0.0,-10.0,10.0,0.0]},"SketchPlane":[{"SketchOrigin":[0.0,0.0,0.0]},{"SketchNormal":[0.0,0.0,1.0]}],"CurveArrArray":[{"Array1Line1":[1.0,0.0,0.0,1.0,1.0,0.0]},{"Array1Line2":[1.0,1.0,0.0,4.4408920985006262E-16,4.4408920985006262E-16,0.0]},{"Array1Line3":[3.3306690738754696E-16,0.0,0.0,1.0,0.0,0.0]}],"Id":2749,"IsSolid":true,"Visible":false,"Name":null,"Type":null,"isPinned":false,"Category":null},"Visible":true,"IsSolid":true,"Id":2749,"Name":"Вращение","Type":"Autodesk.Revit.DB.Revolution","isPinned":false,"Category":null}},"Blends":{},"Sweeps":{},"SweptBlends":{}}