{"Name":"MyCubes","Extrusions":{"2794":{"ExtrusionWrapProperties":{"StartOffset":0.0,"EndOffset":0.82020997375328075,"SketchPlane":[{"SketchOrigin":[0.0,0.0,0.0]},{"SketchNormal":[0.0,0.0,1.0]}],"CurveArrArray":[{"Array1Line1":[-1.8110967696021056,2.7571287385187553,0.0,-1.8110967696021056,1.4447927805135059,0.0]},{"Array1Line2":[-1.8110967696021056,1.4447927805135059,0.0,-3.4515167171086674,1.4447927805135059,0.0]},{"Array1Line3":[-3.4515167171086674,1.4447927805135059,0.0,-3.4515167171086674,2.7571287385187553,0.0]},{"Array1Line4":[-3.4515167171086674,2.7571287385187553,0.0,-1.8110967696021056,2.7571287385187553,0.0]}],"Visible":false,"IsSolid":true,"doc":null,"Id":2794,"Name":null,"Type":null,"isPinned":false,"Category":null},"Visible":true,"IsSolid":true,"doc":null,"Id":2794,"Name":"Выдавливание","Type":"Autodesk.Revit.DB.Extrusion","isPinned":false,"Category":null}},"Revolutions":{},"Blends":{},"Sweeps":{},"SweptBlends":{},"Dimensions":{"2825":{"DimensionWrapProperties":{"ViewName":"Ref. Level","LineAlongDim":{"Line":[-2.5324738042690811,3.8804034097671387,0.0,1.0,4.4408920985006262E-16,0.0]},"ReferenceIds":[[2794,5],[2794,13]],"doc":null,"Id":2825,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":2825,"Name":"Linear","Type":"Autodesk.Revit.DB.Dimension","isPinned":false,"Category":"Autodesk.Revit.DB.Category"}}}