{"Name":"MyCubes","Extrusions":{},"Revolutions":{},"Blends":{"3989":{"BlendWrapProperties":{"TopOffset":1.4763779527559056,"BottomOffset":-1.4763779527559056,"BaseSketchPlane":[{"SketchOrigin":[3.6174497453117382,3.9307644716341503,1.0]},{"SketchNormal":[0.0,0.0,1.0]}],"TopCurveArrArray":[{"Arc1":[1.4806408831545568,1.9653822358170732,0.0,2.1368088621571815,1.9653822358170772,0.0,1.5004267687234851,1.8531709027049772,0.0]},{"Arc2":[2.1368088621571815,1.9653822358170752,0.0,1.4806408831545568,1.9653822358170752,0.0,2.1170229765882538,2.0775935689291711,0.0]}],"BaseCurveArrArray":[{"Line1":[2.62893484640915,1.1451722620637943,0.0,2.62893484640915,2.785592209570356,0.0]},{"Line2":[2.62893484640915,2.785592209570356,0.0,0.98851489890258826,2.785592209570356,0.0]},{"Line3":[0.98851489890258826,2.785592209570356,0.0,0.98851489890258826,1.1451722620637943,0.0]},{"Line4":[0.98851489890258826,1.1451722620637943,0.0,2.62893484640915,1.1451722620637943,0.0]}],"Id":3989,"IsSolid":true,"Visible":false,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"Visible":true,"IsSolid":true,"doc":null,"Id":3989,"Name":"Переход","Type":"Autodesk.Revit.DB.Blend","isPinned":false,"Category":null}},"Sweeps":{},"SweptBlends":{},"Dimensions":{"4023":{"DimensionWrapProperties":{"ViewName":"Ref. Level","LineAlongDim":{"Line":[1.0695438490512785,3.6550856222199206,0.0,1.0,0.0,0.0]},"ReferenceIds":[[3989,11],[3989,3]],"Id":4023,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":4023,"Name":"Linear","Type":"Autodesk.Revit.DB.Dimension","isPinned":false,"Category":"Autodesk.Revit.DB.Category"}}}