{"Name":"RST_basic_sample_project","StructuralColumns":{"1046264":{"StructuralColumnWrapProperties":{"CenterPoint":[-6.3584923968581712,8.8481168681723847,0.0],"FamilySymbolName":"200UB25.4","LevelName":"Level 2","Id":1046264,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046264,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1096385":{"StructuralColumnWrapProperties":{"CenterPoint":[-6.3584923968581641,-10.170912003222689,-1.0658141036401503E-14],"FamilySymbolName":"200UB25.4","LevelName":"Level 2","Id":1096385,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1096385,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1096413":{"StructuralColumnWrapProperties":{"CenterPoint":[3.4840272881811916,8.8481168681694626,-1.0658141036401503E-14],"FamilySymbolName":"200UB25.4","LevelName":"Level 2","Id":1096413,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1096413,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1096419":{"StructuralColumnWrapProperties":{"CenterPoint":[3.4840272881811987,-10.170912003225611,-1.0658141036401503E-14],"FamilySymbolName":"200UB25.4","LevelName":"Level 2","Id":1096419,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1096419,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1098642":{"StructuralColumnWrapProperties":{"CenterPoint":[42.854106028338677,-10.170912003222671,0.0],"FamilySymbolName":"200UB25.4","LevelName":"Ref Beam system","Id":1098642,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1098642,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1114995":{"StructuralColumnWrapProperties":{"CenterPoint":[42.854106028338705,8.8481168681722515,0.0],"FamilySymbolName":"200UB25.4","LevelName":"Foundation","Id":1114995,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1114995,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1173925":{"StructuralColumnWrapProperties":{"CenterPoint":[-1.4372325543384978,-0.66139756752514489,0.0],"FamilySymbolName":"450 x 450mm","LevelName":"Level 1","Id":1173925,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1173925,"Name":"450 x 450mm","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1417448":{"StructuralColumnWrapProperties":{"CenterPoint":[23.169066658259844,-50.398930375924692,0.0],"FamilySymbolName":"HSS63.5X63.5X7.9","LevelName":"Level Lower","Id":1417448,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1417448,"Name":"HSS63.5X63.5X7.9","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1417450":{"StructuralColumnWrapProperties":{"CenterPoint":[23.169066658259847,-49.152211215819435,0.0],"FamilySymbolName":"HSS63.5X63.5X7.9","LevelName":"Level Lower","Id":1417450,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1417450,"Name":"HSS63.5X63.5X7.9","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1417452":{"StructuralColumnWrapProperties":{"CenterPoint":[23.169066658259862,-40.0314763076832,0.0],"FamilySymbolName":"HSS63.5X63.5X7.9","LevelName":"Level Lower","Id":1417452,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1417452,"Name":"HSS63.5X63.5X7.9","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1417454":{"StructuralColumnWrapProperties":{"CenterPoint":[23.169066658259894,-20.346436937604349,0.0],"FamilySymbolName":"HSS63.5X63.5X7.9","LevelName":"Level Lower","Id":1417454,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1417454,"Name":"HSS63.5X63.5X7.9","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1417456":{"StructuralColumnWrapProperties":{"CenterPoint":[23.169066658259908,-12.013103604270748,0.0],"FamilySymbolName":"HSS63.5X63.5X7.9","LevelName":"Level Lower","Id":1417456,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1417456,"Name":"HSS63.5X63.5X7.9","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1417459":{"StructuralColumnWrapProperties":{"CenterPoint":[23.16906665825983,-59.191581294559846,0.0],"FamilySymbolName":"HSS63.5X63.5X7.9","LevelName":"Level Lower","Id":1417459,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1417459,"Name":"HSS63.5X63.5X7.9","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1417475":{"StructuralColumnWrapProperties":{"CenterPoint":[42.854106028338563,-50.398930375924756,0.0],"FamilySymbolName":"HSS63.5X63.5X7.9","LevelName":"Level Lower","Id":1417475,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1417475,"Name":"HSS63.5X63.5X7.9","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1417477":{"StructuralColumnWrapProperties":{"CenterPoint":[42.85410602833857,-49.1522112158195,0.0],"FamilySymbolName":"HSS63.5X63.5X7.9","LevelName":"Level Lower","Id":1417477,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1417477,"Name":"HSS63.5X63.5X7.9","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1417479":{"StructuralColumnWrapProperties":{"CenterPoint":[42.854106028338585,-40.031476307683263,0.0],"FamilySymbolName":"HSS63.5X63.5X7.9","LevelName":"Level Lower","Id":1417479,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1417479,"Name":"HSS63.5X63.5X7.9","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1417481":{"StructuralColumnWrapProperties":{"CenterPoint":[42.85410602833862,-20.346436937604413,0.0],"FamilySymbolName":"HSS63.5X63.5X7.9","LevelName":"Level Lower","Id":1417481,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1417481,"Name":"HSS63.5X63.5X7.9","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1417485":{"StructuralColumnWrapProperties":{"CenterPoint":[42.854106028338549,-59.19158129455991,0.0],"FamilySymbolName":"HSS63.5X63.5X7.9","LevelName":"Level Lower","Id":1417485,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1417485,"Name":"HSS63.5X63.5X7.9","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1432709":{"StructuralColumnWrapProperties":{"CenterPoint":[42.854106028338677,-10.170912003222671,0.0],"FamilySymbolName":"200UB25.4","LevelName":"Foundation","Id":1432709,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1432709,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1436414":{"StructuralColumnWrapProperties":{"CenterPoint":[-16.201012081897542,8.8481168681723847,0.0],"FamilySymbolName":"200UB25.4","LevelName":"Level 2","Id":1436414,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1436414,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1436418":{"StructuralColumnWrapProperties":{"CenterPoint":[-16.201012081897535,-10.170912003222689,0.0],"FamilySymbolName":"200UB25.4","LevelName":"Level 2","Id":1436418,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1436418,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1436521":{"StructuralColumnWrapProperties":{"CenterPoint":[13.326546973220573,8.8481168681665441,0.0],"FamilySymbolName":"200UB25.4","LevelName":"Level 2","Id":1436521,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1436521,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1436526":{"StructuralColumnWrapProperties":{"CenterPoint":[13.32654697322058,-10.17091200322853,0.0],"FamilySymbolName":"200UB25.4","LevelName":"Level 2","Id":1436526,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1436526,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1436688":{"StructuralColumnWrapProperties":{"CenterPoint":[33.011586343299335,8.8481168681722515,0.0],"FamilySymbolName":"200UB25.4","LevelName":"Foundation","Id":1436688,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1436688,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1436726":{"StructuralColumnWrapProperties":{"CenterPoint":[23.169066658259965,8.8481168681722515,0.0],"FamilySymbolName":"200UB25.4","LevelName":"Foundation","Id":1436726,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1436726,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1436859":{"StructuralColumnWrapProperties":{"CenterPoint":[33.011586343299236,-10.170912003222671,0.0],"FamilySymbolName":"200UB25.4","LevelName":"Ref Beam system","Id":1436859,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1436859,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1436866":{"StructuralColumnWrapProperties":{"CenterPoint":[33.011586343299236,-10.170912003222671,0.0],"FamilySymbolName":"200UB25.4","LevelName":"Foundation","Id":1436866,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1436866,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1436901":{"StructuralColumnWrapProperties":{"CenterPoint":[23.169066658259883,-10.170912003222671,0.0],"FamilySymbolName":"200UB25.4","LevelName":"Ref Beam system","Id":1436901,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1436901,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1436907":{"StructuralColumnWrapProperties":{"CenterPoint":[23.169066658259883,-10.170912003222671,0.0],"FamilySymbolName":"200UB25.4","LevelName":"Foundation","Id":1436907,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1436907,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1467946":{"StructuralColumnWrapProperties":{"CenterPoint":[42.854106028338613,-12.013103604270812,0.0],"FamilySymbolName":"HSS63.5X63.5X7.9","LevelName":"Level Lower","Id":1467946,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1467946,"Name":"HSS63.5X63.5X7.9","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"}},"Columns":{},"Beams":{"1046268":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1046268,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046268,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046278":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"88.9x5.0CHS","LevelName":null,"Id":1046278,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046278,"Name":"88.9x5.0CHS","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046281":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"88.9x5.0CHS","LevelName":null,"Id":1046281,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046281,"Name":"88.9x5.0CHS","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046284":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"88.9x5.0CHS","LevelName":null,"Id":1046284,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046284,"Name":"88.9x5.0CHS","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046287":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"88.9x5.0CHS","LevelName":null,"Id":1046287,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046287,"Name":"88.9x5.0CHS","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046290":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"88.9x5.0CHS","LevelName":null,"Id":1046290,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046290,"Name":"88.9x5.0CHS","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046298":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046298,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046298,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046300":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046300,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046300,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046302":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046302,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046302,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046304":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046304,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046304,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046306":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046306,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046306,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046308":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046308,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046308,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046310":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046310,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046310,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046312":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046312,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046312,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046314":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046314,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046314,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046316":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046316,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046316,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046318":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046318,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046318,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046320":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046320,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046320,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046322":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046322,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046322,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046324":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046324,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046324,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046326":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046326,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046326,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046328":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046328,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046328,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046330":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046330,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046330,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046332":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046332,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046332,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046334":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046334,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046334,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046336":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046336,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046336,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046338":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046338,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046338,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046340":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046340,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046340,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046342":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046342,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046342,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046344":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046344,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046344,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046346":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046346,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046346,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046348":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046348,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046348,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046350":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046350,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046350,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046352":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046352,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046352,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046354":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046354,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046354,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046356":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046356,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046356,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046358":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046358,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046358,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046360":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046360,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046360,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046362":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046362,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046362,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046364":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046364,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046364,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046366":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046366,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046366,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046368":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046368,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046368,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046370":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046370,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046370,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046372":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046372,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046372,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046374":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046374,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046374,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046376":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046376,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046376,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046378":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046378,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046378,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046380":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046380,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046380,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046382":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046382,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046382,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046384":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046384,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046384,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046386":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046386,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046386,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046388":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046388,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046388,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046390":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046390,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046390,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046392":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"88.9x5.0CHS","LevelName":null,"Id":1046392,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046392,"Name":"88.9x5.0CHS","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046394":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"88.9x5.0CHS","LevelName":null,"Id":1046394,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046394,"Name":"88.9x5.0CHS","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046396":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"88.9x5.0CHS","LevelName":null,"Id":1046396,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046396,"Name":"88.9x5.0CHS","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046398":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"88.9x5.0CHS","LevelName":null,"Id":1046398,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046398,"Name":"88.9x5.0CHS","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046400":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"88.9x5.0CHS","LevelName":null,"Id":1046400,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046400,"Name":"88.9x5.0CHS","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046402":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"88.9x5.0CHS","LevelName":null,"Id":1046402,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046402,"Name":"88.9x5.0CHS","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046404":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046404,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046404,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046406":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046406,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046406,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046408":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046408,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046408,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046410":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046410,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046410,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046412":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046412,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046412,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046414":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046414,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046414,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046416":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046416,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046416,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046418":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046418,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046418,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046420":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046420,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046420,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046422":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046422,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046422,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046424":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046424,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046424,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046426":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046426,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046426,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046428":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046428,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046428,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046430":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046430,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046430,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046432":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046432,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046432,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046434":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046434,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046434,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046436":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046436,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046436,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046438":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046438,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046438,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046440":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046440,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046440,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046442":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046442,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046442,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046444":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046444,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046444,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046446":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046446,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046446,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046448":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046448,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046448,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046450":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046450,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046450,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046452":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046452,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046452,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046454":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046454,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046454,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046456":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046456,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046456,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046458":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046458,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046458,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046460":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046460,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046460,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046462":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046462,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046462,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046464":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046464,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046464,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046466":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046466,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046466,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046468":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046468,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046468,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046470":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046470,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046470,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046472":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046472,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046472,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046474":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046474,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046474,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046476":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046476,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046476,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046478":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046478,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046478,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046480":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046480,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046480,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046482":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046482,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046482,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046484":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046484,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046484,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046486":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046486,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046486,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046488":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046488,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046488,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046490":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046490,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046490,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046492":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046492,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046492,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046494":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046494,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046494,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046496":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046496,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046496,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046498":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1046498,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046498,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046503":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"88.9x5.0CHS","LevelName":null,"Id":1046503,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046503,"Name":"88.9x5.0CHS","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046512":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"88.9x5.0CHS","LevelName":null,"Id":1046512,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046512,"Name":"88.9x5.0CHS","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046542":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"30mm","LevelName":null,"Id":1046542,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046542,"Name":"30mm","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046544":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"30mm","LevelName":null,"Id":1046544,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046544,"Name":"30mm","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046546":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"30mm","LevelName":null,"Id":1046546,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046546,"Name":"30mm","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046548":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"30mm","LevelName":null,"Id":1046548,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046548,"Name":"30mm","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046550":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"30mm","LevelName":null,"Id":1046550,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046550,"Name":"30mm","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046552":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"30mm","LevelName":null,"Id":1046552,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046552,"Name":"30mm","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046554":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"30mm","LevelName":null,"Id":1046554,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046554,"Name":"30mm","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046556":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"30mm","LevelName":null,"Id":1046556,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046556,"Name":"30mm","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046558":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"30mm","LevelName":null,"Id":1046558,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046558,"Name":"30mm","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046560":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"30mm","LevelName":null,"Id":1046560,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046560,"Name":"30mm","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046562":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"30mm","LevelName":null,"Id":1046562,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046562,"Name":"30mm","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046564":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"30mm","LevelName":null,"Id":1046564,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046564,"Name":"30mm","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046566":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"30mm","LevelName":null,"Id":1046566,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046566,"Name":"30mm","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046568":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"30mm","LevelName":null,"Id":1046568,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046568,"Name":"30mm","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046570":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"30mm","LevelName":null,"Id":1046570,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046570,"Name":"30mm","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1046572":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"30mm","LevelName":null,"Id":1046572,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1046572,"Name":"30mm","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1096387":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1096387,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1096387,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1096415":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1096415,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1096415,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1096421":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1096421,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1096421,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1098644":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1098644,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1098644,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1114997":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1114997,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1114997,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1116436":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1116436,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1116436,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1116461":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1116461,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1116461,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1116483":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1116483,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1116483,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1116502":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1116502,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1116502,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1116979":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1116979,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1116979,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1117017":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1117017,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1117017,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1117037":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1117037,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1117037,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1117066":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1117066,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1117066,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1117306":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1117306,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1117306,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1174038":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1174038,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1174038,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1175513":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1175513,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1175513,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1175555":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1175555,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1175555,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1175999":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1175999,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1175999,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1176035":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1176035,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1176035,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1176046":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1176046,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1176046,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1176054":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1176054,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1176054,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":true,"Category":"Autodesk.Revit.DB.Category"},"1407777":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"SC15012","LevelName":null,"Id":1407777,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1407777,"Name":"SC15012","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1417275":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1417275,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1417275,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1417277":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1417277,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1417277,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1417279":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1417279,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1417279,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1417281":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1417281,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1417281,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1417462":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200PFC","LevelName":null,"Id":1417462,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1417462,"Name":"200PFC","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1417464":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200PFC","LevelName":null,"Id":1417464,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1417464,"Name":"200PFC","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1417466":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200PFC","LevelName":null,"Id":1417466,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1417466,"Name":"200PFC","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1417469":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200PFC","LevelName":null,"Id":1417469,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1417469,"Name":"200PFC","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1417471":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200PFC","LevelName":null,"Id":1417471,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1417471,"Name":"200PFC","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1417473":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200PFC","LevelName":null,"Id":1417473,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1417473,"Name":"200PFC","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1417487":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200PFC","LevelName":null,"Id":1417487,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1417487,"Name":"200PFC","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1436416":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1436416,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1436416,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1436420":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1436420,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1436420,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1436523":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1436523,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1436523,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1436528":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1436528,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1436528,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1436690":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1436690,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1436690,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1436728":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1436728,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1436728,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1436861":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1436861,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1436861,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1436903":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1436903,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1436903,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1437055":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"88.9x5.0CHS","LevelName":null,"Id":1437055,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1437055,"Name":"88.9x5.0CHS","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1437083":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"88.9x5.0CHS","LevelName":null,"Id":1437083,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1437083,"Name":"88.9x5.0CHS","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1437167":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"88.9x5.0CHS","LevelName":null,"Id":1437167,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1437167,"Name":"88.9x5.0CHS","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1437215":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"88.9x5.0CHS","LevelName":null,"Id":1437215,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1437215,"Name":"88.9x5.0CHS","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1437249":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"88.9x5.0CHS","LevelName":null,"Id":1437249,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1437249,"Name":"88.9x5.0CHS","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"},"1438725":{"BeamWrapProperties":{"AxisCurve":null,"FamilySymbolName":"200UB25.4","LevelName":null,"Id":1438725,"doc":null,"Name":null,"Type":null,"isPinned":false,"Category":null},"doc":null,"Id":1438725,"Name":"200UB25.4","Type":"Autodesk.Revit.DB.FamilyInstance","isPinned":false,"Category":"Autodesk.Revit.DB.Category"}}}